<Project>

	<!-- Include ONI-Libs submodule -->
	<Import Project="$(SolutionDir)/GameLibs.props"/>
	<Import Project="$(SolutionDir)/GameLibs.user.props" Condition="Exists('$(SolutionDir)/GameLibs.user.props')"/>

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ClearOutputDirectory>true</ClearOutputDirectory>
		<GenerateDependencyFile>false</GenerateDependencyFile>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<Optimize>false</Optimize>
		<DefineConstants>$(DefineConstants);DEV</DefineConstants>
	</PropertyGroup>

</Project>