<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ModID>Neutronium_ElementsExample</ModID>
		<ModName>Neutronium Elements Example</ModName>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="$(SolutionDir)\NeutroniumApi.MergeLib\NeutroniumApi.MergeLib.csproj">
			<PrivateAssets>all</PrivateAssets>
		</ProjectReference>
		<Reference Include="UnityEngine">
			<HintPath>$(UnityLibsFolder)/UnityEngine.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(UnityLibsFolder)/UnityEngine.CoreModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>$(GameLibsFolder)/Assembly-CSharp.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Assembly-CSharp-firstpass">
			<HintPath>$(GameLibsFolder)/Assembly-CSharp-firstpass.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>$(GameLibsFolder)/0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>
