<Project>

	<!-- Include ONI-Libs submodule -->
	<Import Project="$(SolutionDir)/GameLibs.props"/>
	<Import Project="$(SolutionDir)/GameLibs.user.props" Condition="Exists('$(SolutionDir)/GameLibs.user.props')"/>

	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<DebugSymbols>false</DebugSymbols>
		<GenerateDependencyFile>false</GenerateDependencyFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.37">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>