<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Neutronium.MergeLib.Api</RootNamespace>
		<CoreApiLibrary>$(SolutionDir)/NeutroniumApi.Interfaces/bin/$(Configuration)/netstandard2.0/NeutroniumApi.Interfaces.dll</CoreApiLibrary>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>

	<ItemGroup>
		<CompilerVisibleProperty Include="CoreApiLibrary" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\NeutroniumApi.CodeGen\NeutroniumApi.CodeGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="False" />
	</ItemGroup>

</Project>