<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Neutronium.MergeLib.Api</RootNamespace>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>

	<ItemGroup>
		<CompilerVisibleProperty Include="SolutionDir" />
		<CompilerVisibleProperty Include="UnityLibsFolder" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(SolutionDir)\NeutroniumApi.CodeGen\NeutroniumApi.CodeGen.csproj"
		                  OutputItemType="Analyzer" ReferenceOutputAssembly="False" />
		<Reference Include="UnityEngine">
			<HintPath>$(UnityLibsFolder)/UnityEngine.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(UnityLibsFolder)/UnityEngine.CoreModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>